language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
      services: mysql
      addons:
        apt:
          packages: libmariadbclient-dev
    - dist: trusty
      services: mysql    
      addons:
        apt:
          packages: libmysqlclient-dev
    - dist: xenial
      services: mysql    
      addons:
        apt:
          packages: libmariadbd-dev
    - dist: xenial
      services: mysql    
      addons:
        apt:
          packages: libmysqlclient-dev
    - os: osx
      before_install:
        - rm -f /etc/my.cnf
        - brew install mariadb
        - brew services start mariadb
    - os: osx
      before_install:
        - brew install mysql
        - mysql.server start
    - os: osx
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      r_check_args: '--no-tests'
      before_script: 'echo no sql server, only testing build'
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "CREATE USER 'billy'@'localhost' IDENTIFIED BY 'supersecret';" -uroot
  - printf "[rs-dbi]\nusername=billy\npassword=supersecret\n" > ~/.my.cnf
