# Info:
# https://docs.travis-ci.com/user/languages/r/
# https://docs.travis-ci.com/user/database-setup/#MySQL

language: r
cache: packages
sudo: false

services:
  - MySQL
addons:
  apt:
    packages:
      - libmysqlclient-dev

#r_check_revdep: true

r_github_packages:
  - rstats-db/DBI
  - jimhester/covr
  - rstats-db/DBItest@production

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
